name: Construção do artefato

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout projeto
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKER_HUB_USERNAME}}
          password: ${{vars.DOCKER_HUB_TOKEN}}

      - name: Constrói e envia imagem docker
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{vars.DOCKER_HUB_USERNAME}}/projeto_go:latest,${{vars.DOCKER_HUB_USERNAME}}/projeto_go:${{github.sha}}      