# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Verificações de código

on:
  pull_request:
    branches: [ "main" ]

jobs:

  check:
    environment: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout projeto
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Inicia banco
      run: docker compose up -d postgres

    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.59
        args: controllers/ database/ models/ routes/

    - name: Test
      run: DB_HOST=${{ vars.DB_HOST }} DB_PASSWORD=${{ vars.DB_PASSWORD }} DB_USER=${{ vars.DB_USER }} DB_NAME=${{ vars.DB_NAME }} DB_PORT=${{ vars.DB_PORT }} go test -v main_test.go
    
    - name: Build
      run: go build main.go


